Simplify functionality - remove upload functionality - remove zenity dependency and all dialogs - add ability to get password from gnome-keyring - simplify functionality: just copy public link to clipboard from context menu - fix some minor bugs

diff --git a/shareLinkCreator b/shareLinkCreator
--- a/shareLinkCreator
+++ b/shareLinkCreator
@@ -7,230 +7,73 @@
 # This program is free software released under the MIT License, for more details
 # see LICENSE.txt or http://opensource.org/licenses/MIT
 #
-# Description: 
-#
-# The program was developed for the Thunar file manager but it should also
-# works with other file managers which provide similar possibilities to
-# integrate shell scripts. For example I got some feedback that it also works
-# nicely with Dolphin and Nautilus.
-#
-# This script can be integrated in the Thunar file manager as a "custom
-# action". If you configure the "custom action" in Thunar, make sure to pass
-# the paths of all selected files to the program using the "%F" parameter. The
-# program expects the absolute path to the files. Once the custom action is
-# configured you can execute the program from the right-click context menu. The
-# program works for all file types and also for directories. Once the script
-# gets executed it will first upload the files/directories to your ownCloud and
-# afterwards it will generate a public link to access them. The link will be
-# copied directly to your clipboard and a dialog will inform you about the
-# URL. If you uploaded a single file or directory than the file/directory will
-# be created directly below your "uploadTarget" as defined below. If you
-# selected multiple files, than the programm will group them together in a
-# directory named with the current timestamp.
-#
 # Before you can use the program you need to adjust at least the "baseURL",
-# "username" and "password" config parameter below. If you keep "username"
-# and/or "password" empty a dialog will show up and ask for the credentials.
+# "shareURL", "localDir" and "username" config parameters.
 #
 # Requirements:
 #
 # - curl
 # - xclip
-# - zenity
+# - python-gnomekeyring
 
 # load config parameters
 . "$(dirname $0)/config"
 
-# constants
-TRUE=0
-FALSE=1
+notify() {
+    notify-send "ownCloud" "$1" -i owncloud -t 3000
+}
 
-webdavURL="$baseURL/remote.php/webdav"
-url=$(echo "$webdavURL/$uploadTarget" | sed 's/\ /%20/g')
-shareAPI="$baseURL/ocs/v1.php/apps/files_sharing/api/v1/shares"
-curlOpts=""
-if [ -n "$cacert" ]; then
-    curlOpts="$curlOpts --cacert $cacert"
+error() {
+    notify "Error: $1"
+    exit 1
+}
+
+if [ $# != 1 ]; then
+    error "Please select one file"
+elif [ ! -f "$1" ]; then
+    error "File not found: $1"
 fi
 
-# check if base dir for file upload exists
-baseDirExists() {
-    if curl -u "$username":"$password" --output /dev/null $curlOpts --silent --head --fail "$url"; then
-        return $FALSE
-    fi
-    return $TRUE
-}
+file=$1
 
-checkCredentials() {
-    curl -u "$username":"$password" $curlOpts --output /dev/null --silent --fail "$webdavURL"
-    if [ $? != 0 ]; then
-        msg="Username or password does not match"
-        if [ $usezenity -eq 1 ]; then
-            zenity --error --title="ownCloud Public Link Creator" --text=$msg
-            exit 1
-        else
-            echo $msg
-            exit 1
-        fi
-    fi
-}
+if [ "${file##$localDir}" == "$file" ]; then
+    error "Please select file from $localDir"
+fi
 
-# upload files, first parameter will be the upload target from the second
-# parameter on we have the list of files
-uploadFiles() {
-    for filePath in "${@:2}"
-    do
-        basename=$(basename "$filePath")
-        basename=$(echo "$basename" | sed 's/\ /%20/g')
-        if [ -f "$filePath" ]; then
-            curl -u "$username":"$password" $curlOpts -T "$filePath" "$1/$basename"
-            count=$(($count+1))
-            if [ $usezenity -eq 1 ]; then
-                echo $(($count*100/$numOfFiles)) >&3;
-            fi
-        else
-            curl -u "$username":"$password" $curlOpts -X MKCOL "$1/$basename"
-            uploadDirectory "$1/$basename" "$filePath"
-        fi
-    done
-    return $TRUE
-}
+file=$(echo "$1" | sed "s#^$(echo $localDir)##g")
 
-# upload a directory recursively, first parameter contains the upload target
-# and the second parameter contains the path to the local directory
-uploadDirectory() {
-    while read filePath; do
-        filePath=$(basename "$filePath")
-        urlencodedFilePath=$(echo "$filePath" | sed 's/\ /%20/g')
-        if [ -d "$2/$filePath" ]; then
-            curl -u "$username":"$password" $curlOpts -X MKCOL "$1/$urlencodedFilePath"
-            uploadDirectory "$1/$urlencodedFilePath" "$2/$filePath"
-        else
-            curl -u "$username":"$password" $curlOpts -T "$2/$filePath" "$1/$urlencodedFilePath"
-            count=$(($count+1))
-            if [ $usezenity -eq 1 ]; then
-                echo $(($count*100/$numOfFiles)) >&3;
-            fi
-        fi
-    done < <(find "$2" -mindepth 1 -maxdepth 1)
-
-}
+webdavURL="$baseURL/remote.php/webdav"
+url=$(echo "$webdavURL/$file" | sed 's/\ /%20/g')
+shareAPI="$baseURL/ocs/v1.php/apps/files_sharing/api/v1/shares"
 
 # create public link share, first parameter contains the path of the shared file/folder
 createShare() {
-    result=$(curl -u "$username":"$password" $curlOpts --silent "$shareAPI" -d path="$1" -d shareType=3)
-    shareLink=$(echo $result | sed -e 's/.*<url>\(.*\)<\/url>.*/\1/')
-    shareLink=$(echo $shareLink | sed 's/\&amp;/\&/')
-    echo $shareLink | xclip -sel clip
-    return $TRUE
-
-}
-
-# if no password is set in the script we ask the user to enter them
-askForPassword() {
-    ENTRY=`zenity --password --title="ownCloud Public Link Creator"`
-
-    case $? in
-        0)
-	    password=`echo $ENTRY | cut -d'|' -f1`
-	    ;;
-        1)
-            exit 0;;
-        -1)
-            exit 1;;
-    esac
-}
-
-# if no username/password is set in the script we ask the user to enter them
-askForUserPassword() {
-    ENTRY=`zenity --password --username --title="ownCloud Public Link Creator"`
-
-    case $? in
-        0)
-	    username=`echo $ENTRY | cut -d'|' -f1`
-	    password=`echo $ENTRY | cut -d'|' -f2`
-	    ;;
-        1)
-            exit 0;;
-        -1)
-            exit 1;;
-    esac
-}
-
-askForUserPasswordNonZenity() {
-    read -p "Username: " username
-    read -s -p "Password: " password
-    echo
-    if [ -z $password ] || [ -z $username ]; then
-        exit 1
+    echo -n 'Getting a link from server... '
+    result=$(curl -u "$username":"$password" --silent "$shareAPI" --connect-timeout 4 -d path="$1" -d shareType=3)
+    if [ $? != 0 ]; then
+        error "Cannot complete the request"
+    fi
+    echo $result | grep -q "<status>failure</status>"
+    if [ $? == 0 ]; then
+        error "File is not uploaded yet"
+    else
+        shareCode=$(echo $result | sed -e 's/.*<url>\(.*\)<\/url>.*/\1/')
+        shareCode=$(echo $shareCode | sed 's/.*\&amp;t=//')
+        shareLink=$(echo $shareURL$shareCode)
+        echo -n $shareLink | xclip -sel clip
+        echo 'done.'
     fi
 }
 
-askForPasswordNonZenity() {
-    read -s -p "Password for $username: " password
-    echo
-    if [ -z $password ] || [ -z $username ]; then
-        exit 1
-    fi
-}
-
-
-
-
-
-if [ -z $password ] && [ -z $username ]; then
-# ask for both password and username
-    if [ $usezenity -eq 1 ]; then askForUserPassword
-    else askForUserPasswordNonZenity
-    fi
-elif [ -z $password ]; then
-# ask for password only
-    if [ $usezenity -eq 1 ]; then askForPassword
-    else askForPasswordNonZenity
-    fi
+if [ -z $username ]; then
+    error "Please specify username in config file"
 fi
 
+password=$(python "$(dirname $0)/gkeyring.py" "$username:$baseURL/")
 
-checkCredentials
-
-msg="Uploading files and generating a public link"
-if [ $usezenity -eq 1 ]; then
-    exec 3> >(zenity --progress --title="ownCloud Public Link Creator" --text=$msg --auto-kill --auto-close --percentage=0 --width=400)
-else
-    echo $msg
+if [ -z $password ]; then
+    error "Cannot found stored password"
 fi
 
-
-numOfFiles=$(find "$@" -type f | wc -l)
-count=0
-
-if baseDirExists; then
-    curl -u "$username":"$password" $curlOpts -X MKCOL "$url"
-fi
-
-# if we have more than one file selected we create a folder with
-# the current timestamp
-if [ $# -gt 1 ]; then
-    share=$(date +%s)
-    url="$url/$share"
-    curl -u "$username":"$password" $curlOpts -X MKCOL "$url"
-elif [ $# -eq 1 ]; then
-    share=$(basename "$1")
-else
-    msg="no file was selected!"
-    if [ $usezenity -eq 1 ]; then zenity --error --title="ownCloud Public Link Creator" --text=$msg
-    else echo $msg
-    fi
-    exit 1
-fi
-
-if uploadFiles $url "$@"; then
-    createShare "/$uploadTarget/$share"
-fi
-
-output="File uploaded successfully. Following public link was generated and copied to your clipboard: $shareLink"
-if [ $usezenity -eq 1 ]; then
-    zenity --info --title="ownCloud Public Link Creator" --text="$output" --no-markup
-else
-    echo $output
-fi
+createShare "/$file"
+notify "The link has been copied to clipboard"
